apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
#  namespace: kube-ops
spec:
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
#      serviceAccountName: jenkins2
      containers:
      - image: hub.ityy.ultrapower.com.cn:5050/jen-demo/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
